/**
 * Type definitions for auto-generated help.json file
 * Generated by services/dataUpdater.ts:exportCommandDocs()
 */

/**
 * Single command entry in help.json
 */
export interface HelpCommand {
    name: string;
    description: string;
    usage: string[];
    options: unknown[];
    permLevel: number;
    devServerOnly: boolean;
    contexts: unknown;
    enabled: boolean;
}

/**
 * Metadata about the help.json file generation
 */
export interface HelpMetadata {
    generatedAt: string;
    totalCommands: number;
    categories: number;
}

/**
 * Category entry in help.json
 */
export interface HelpCategory {
    description: string;
    commands: HelpCommand[];
}

/**
 * Root structure of help.json
 * Contains metadata and category-keyed command lists
 */
export interface HelpJSON {
    metadata: HelpMetadata;
    [category: string]: HelpCategory | HelpMetadata;
}
