name: Feature request
description: Request a new feature or changes to an existing one (New command, Patreon feature, change in output)
labels: [feature request]
body:
  - type: markdown
    attributes:
      value: |
        We can only implement features that are possible within the limitation of what info is available from the game, and what Discord can display.
        Use Discord for questions: https://discord.gg/FfwGvhr
  - type: textarea
    id: description
    attributes:
      label: Feature
      description: A clear and concise description of what the problem is, or what feature you want to be implemented.
      placeholder: A new command idea..., X command's output would look better as..., SWGoH has recently released..., A good addition would be...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Ideal solution or implementation
      description: A clear and concise description of what you want to happen, sample input and output (What you want to see the bot spit out given what you put in).
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions or implementations
      description: A clear and concise description of any alternative solutions or features you have considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Other context
      description: Any other context, screenshots, or file uploads that help us understand your feature request.
